spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdata?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
server:
  port: 8080
mybatis:
#  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.example.springboot_dzy.pojo
